apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  # slector is how the deployment will find the pods it will create
  selector:
    matchLabels:
      app: auth
  # template is how to create each individual pod in this deployment
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: hamzahhameed9797/auth
---
# service - deaafult type for service is cluster ip service
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
